package org.velosaurus.demo.springbootdemo.dao;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.stereotype.Service;
import org.velosaurus.demo.springbootdemo.entity.Employee;

import java.util.List;

@Service
@RepositoryRestResource(path = "employees")  // Path for autogenerated endpoint
public interface EmployeeRepository extends JpaRepository<Employee, Integer> {
    // all methods are implemented by interface!

    // add method to sort by last name
    // https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details
    public List<Employee> findAllByOrderByLastNameAsc();
}
